# Generated by Django 4.2.16 on 2024-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('done', 'Done'), ('abandoned', 'Abandoned'), ('canceled', 'Canceled')], default='in_progress', max_length=20),
        ),
    ]
